project:
    type: website
    output-dir: docs
    resources:
        - static
        - game-implementations

website:
    title: "Games We Play"
    navbar:
        left:
            - all_games.qmd
        tools:
            - icon: github
              href: https://github.com/gamesweplay-ccl/gamesweplay-ccl.github.io
    favicon: static/images/ccl_logo.png

format:
    html:
        theme: litera
        toc: false
        page-layout: full
        anchor-sections: false
        include-in-header:
            - text: |
                  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
        mainfont: "Omnes"
        headingfont: "Omnes"
